# Generated by Django 6.0.6 on 2026-07-05 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('direct_swap', 'Direct Swap'), ('partial_overlap', 'Partial Overlap'), ('field_relevant', 'Field Relevant')], max_length=32)),
                ('score', models.PositiveIntegerField(default=0)),
                ('rationale', models.CharField(max_length=255)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_match_suggestions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_match_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'id'],
                'indexes': [models.Index(fields=['source_user', 'suggestion_type'], name='swaps_match_source__79b057_idx'), models.Index(fields=['target_user', 'suggestion_type'], name='swaps_match_target__840b6d_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_user', 'target_user'), name='unique_match_suggestion_per_source_target')],
            },
        ),
    ]
