# Generated by Django 6.0.6 on 2026-07-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('auth', 'Authentication'), ('verification', 'Verification'), ('swap', 'Swap'), ('message', 'Message'), ('session', 'Session'), ('course', 'Course'), ('enrollment', 'Enrollment'), ('event', 'Event'), ('opportunity', 'Opportunity'), ('community', 'Community'), ('certificate', 'Certificate'), ('admin', 'Admin')], max_length=32),
        ),
    ]
