DOMAIN_ENTITIES = {
    "User": "Base account for regular users and admins.",
    "Organization": "Organization account/profile with type and trust state.",
    "OrganizationVerification": "Verification review record for organization trust workflows.",
    "Skill": "Structured skill taxonomy record.",
    "UserSkill": "User-to-skill relationship with direction and experience metadata.",
    "FieldInterest": "User-declared academic, professional, or domain focus.",
    "MatchSuggestion": "System-generated compatibility or recommendation record.",
    "SkillSwapRequest": "Request lifecycle record for skill exchange.",
    "LearningSession": "Planned or completed session tied to learning activity.",
    "CourseProgram": "Structured course or program offering.",
    "CourseModule": "Module or grouped lesson segment inside a course.",
    "LessonItem": "Individual learning item such as a video, resource, checklist, or assessment.",
    "Enrollment": "Learner participation and progression record.",
    "FinancialAccount": "Monetization readiness and payout configuration record.",
    "AssignmentResource": "Learning content or assessment artifact.",
    "MessageThread": "Conversation channel for participant coordination.",
    "RatingReview": "Participation-based review or rating record.",
    "Opportunity": "Job, internship, volunteer role, or similar listing.",
    "JobApplication": "In-platform application and pipeline-state record.",
    "CommunityGroup": "Field-based or interest-based user community.",
    "Event": "Scheduled event, meetup, workshop, or community activity.",
    "EventRSVP": "RSVP or registration record for an event.",
    "CommunityActivity": "Community-service or collaboration initiative record.",
    "ServiceCredit": "Verified contribution or impact record.",
    "Certificate": "Completion or verification artifact with lookup reference.",
    "CategorySuggestion": "Requested addition to a controlled category list.",
    "Notification": "System alert, reminder, or workflow update.",
    "AuditLog": "Important admin or security-sensitive event record.",
    "AIFeatureCapability": "Shared rollout and fallback contract for an AI-enabled product capability.",
}

CORE_DOMAIN_STATUS_FIELDS = {
    "Organization.verification_status": "Trust state used across public and monetization-sensitive surfaces.",
    "SkillSwapRequest.status": "Lifecycle state for swaps from request to completion or cancellation.",
    "LearningSession.status": "Lifecycle state for planned and completed sessions.",
    "CourseProgram.status": "Publication state for course or program availability.",
    "Enrollment.status": "Participation state for learner enrollment and progress.",
    "FinancialAccount.status": "Readiness state for monetization and payout setup.",
    "Opportunity.status": "Lifecycle state of an opportunity listing.",
    "JobApplication.status": "Candidate pipeline state for in-platform applications.",
    "Event.status": "Lifecycle state of an event.",
    "CommunityGroup.visibility": "Access level for public or member-only collaboration spaces.",
    "ServiceCredit.status": "Verification state for contribution or impact records.",
    "Certificate.status": "Trust state for verifiable certificate records.",
    "RatingReview.context": "Source context for participation-based review workflows.",
    "Notification.type": "Workflow or system event category for alerts.",
    "AIFeatureCapability.rollout_state": "Whether a feature is disabled, AI-ready, or operating in fallback-only mode.",
}
