# Generated by Django 6.0.6 on 2026-07-06 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("swaps", "0002_skillswaprequest_skillswapstatushistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("scheduled_start_at", models.DateTimeField()),
                ("scheduled_end_at", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("meeting_url", models.URLField(blank=True)),
                ("meeting_notes", models.CharField(blank=True, max_length=255)),
                ("location_note", models.CharField(blank=True, max_length=255)),
                ("completion_notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_learning_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "swap_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_sessions",
                        to="swaps.skillswaprequest",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_start_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="learningsession",
            index=models.Index(fields=["swap_request", "status"], name="sessions_le_swap_re_8b7ae5_idx"),
        ),
        migrations.AddIndex(
            model_name="learningsession",
            index=models.Index(fields=["scheduled_start_at"], name="sessions_le_schedul_4d5eb5_idx"),
        ),
    ]
