# Generated by Django 6.0.6 on 2026-07-06 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='learningsession',
            new_name='learning_se_swap_re_674951_idx',
            old_name='sessions_le_swap_re_8b7ae5_idx',
        ),
        migrations.RenameIndex(
            model_name='learningsession',
            new_name='learning_se_schedul_83da68_idx',
            old_name='sessions_le_schedul_4d5eb5_idx',
        ),
    ]
