# Generated by Django 6.0.6 on 2026-07-05 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swaps', '0002_skillswaprequest_skillswapstatushistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_message_threads', to=settings.AUTH_USER_MODEL)),
                ('swap_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_thread', to='swaps.skillswaprequest')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('resource', 'Resource')], default='text', max_length=16)),
                ('content', models.TextField(blank=True)),
                ('resource_url', models.URLField(blank=True)),
                ('resource_label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.messagethread')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['updated_at'], name='messaging_m_updated_535f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='threadmessage',
            index=models.Index(fields=['thread', 'created_at'], name='messaging_t_thread__335fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='threadmessage',
            index=models.Index(fields=['sender', 'created_at'], name='messaging_t_sender__41ee5a_idx'),
        ),
    ]
