# Generated by Django 6.0.6 on 2026-07-06 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messagethreadreadstate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagethreadreadstate',
            new_name='messaging_m_thread__0b527d_idx',
            old_name='messaging_m_thread__bbf8c8_idx',
        ),
        migrations.RenameIndex(
            model_name='messagethreadreadstate',
            new_name='messaging_m_user_id_a1a8d4_idx',
            old_name='messaging_m_user_id_2b37bc_idx',
        ),
    ]
