# Generated by Django 6.0.6 on 2026-07-09 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveMonitoringConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('recommendations', 'Recommendations'), ('learning_guidance', 'Learning Guidance'), ('assignment_feedback', 'Assignment Feedback'), ('cognitive_monitoring', 'Cognitive Monitoring')], default='cognitive_monitoring', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=32)),
                ('policy_version', models.CharField(max_length=32)),
                ('allowed_signals', models.JSONField(blank=True, default=list)),
                ('surfaces', models.JSONField(blank=True, default=list)),
                ('source_surface', models.CharField(blank=True, max_length=64)),
                ('disclosure_acknowledged', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_monitoring_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'status'], name='ai_cognitiv_user_id_10fb82_idx'), models.Index(fields=['feature_key', 'status'], name='ai_cognitiv_feature_837c58_idx'), models.Index(fields=['granted_at'], name='ai_cognitiv_granted_06a311_idx')],
            },
        ),
    ]
