# Generated by Django 6.0.6 on 2026-07-09 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('courses', '0005_courseprogram_admin_review_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveMonitoringCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(blank=True, max_length=64)),
                ('mood_label', models.CharField(choices=[('energized', 'Energized'), ('steady', 'Steady'), ('tired', 'Tired'), ('distracted', 'Distracted'), ('stuck', 'Stuck'), ('overwhelmed', 'Overwhelmed')], default='steady', max_length=32)),
                ('focus_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('energy_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stress_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reflection_note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adaptive_monitoring_checkins', to='courses.courseprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_monitoring_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_adaptive_user_id_9d61cc_idx'), models.Index(fields=['course_program', 'created_at'], name='ai_adaptive_course__df235b_idx'), models.Index(fields=['mood_label', 'created_at'], name='ai_adaptive_mood_la_ba3d59_idx')],
            },
        ),
    ]
