# Generated by Django 6.0.6 on 2026-07-09 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('communities', '0001_initial'),
        ('courses', '0005_courseprogram_admin_review_notes_and_more'),
        ('events', '0004_event_admin_review_fields'),
        ('organizations', '0004_organization_is_suspended_organization_moderated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecreditrecord',
            name='community_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_credit_records', to='communities.communitygroup'),
        ),
        migrations.AddField(
            model_name='servicecreditrecord',
            name='course_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_credit_records', to='courses.courseprogram'),
        ),
        migrations.AddField(
            model_name='servicecreditrecord',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_credit_records', to='events.event'),
        ),
        migrations.AddField(
            model_name='servicecreditrecord',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_service_credit_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicecreditrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_credit_records', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='servicecreditrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_credit_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='service_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.servicecreditrecord'),
        ),
        migrations.AddIndex(
            model_name='servicecreditrecord',
            index=models.Index(fields=['organization', 'status'], name='certificate_organiz_c7bfde_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecreditrecord',
            index=models.Index(fields=['user', 'status'], name='certificate_user_id_b91fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['organization', 'status'], name='certificate_organiz_22416c_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', 'status'], name='certificate_user_id_42f10a_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['source_type', 'status'], name='certificate_source__931399_idx'),
        ),
    ]
