# Generated by Django 6.0.4 on 2026-07-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogram',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='difficulty',
            field=models.CharField(default='beginner', max_length=32),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='enrollment_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='price_currency',
            field=models.CharField(default='ETB', max_length=8),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.courseprogram')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('video', 'Video'), ('resource', 'Resource'), ('checklist', 'Checklist'), ('assessment', 'Assessment'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('reading', 'Reading')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('content_url', models.URLField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('progression_gate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_items', to='courses.coursemodule')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
