# Generated by Django 6.0.4 on 2026-07-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseprogram_category_courseprogram_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to='courses.enrollment')),
                ('lesson_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_progresses', to='courses.lessonitem')),
            ],
            options={
                'ordering': ['lesson_item__sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'lesson_item'), name='unique_lesson_progress_per_enrollment')],
            },
        ),
    ]
