# Generated by Django 6.0.6 on 2026-07-07 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lessonitem_checklist_items_lessonitem_content_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogram',
            name='admin_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='admin_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_course_programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
