# Generated by Django 6.0.6 on 2026-07-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseprogram_admin_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogram',
            name='auto_issue_service_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='offering_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('community_service', 'Community Service')], default='standard', max_length=32),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='service_credit_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='service_credit_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='service_credit_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
