# Generated by Django 6.0.6 on 2026-07-06 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('events', '0001_initial'),
        ('swaps', '0002_skillswaprequest_skillswapstatushistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('skill_swap', 'Skill Swap'), ('course', 'Course'), ('event', 'Event')], max_length=16)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.courseprogram')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.enrollment')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event')),
                ('event_rsvp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.eventrsvp')),
                ('reviewee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL)),
                ('swap_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='swaps.skillswaprequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_review_score_between_1_and_5'), models.UniqueConstraint(condition=models.Q(('context', 'skill_swap')), fields=('reviewer', 'swap_request'), name='unique_skill_swap_review_per_reviewer'), models.UniqueConstraint(condition=models.Q(('context', 'course')), fields=('reviewer', 'enrollment'), name='unique_course_review_per_reviewer'), models.UniqueConstraint(condition=models.Q(('context', 'event')), fields=('reviewer', 'event_rsvp'), name='unique_event_review_per_reviewer')],
            },
        ),
    ]
