# Generated by Django 6.0.6 on 2026-07-06 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('events', '0001_initial'),
        ('reviews', '0001_initial'),
        ('swaps', '0002_skillswaprequest_skillswapstatushistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ratingreview',
            name='unique_skill_swap_review_per_reviewer',
        ),
        migrations.RemoveConstraint(
            model_name='ratingreview',
            name='unique_course_review_per_reviewer',
        ),
        migrations.RemoveConstraint(
            model_name='ratingreview',
            name='unique_event_review_per_reviewer',
        ),
        migrations.AddConstraint(
            model_name='ratingreview',
            constraint=models.UniqueConstraint(fields=('reviewer', 'swap_request'), name='unique_skill_swap_review_per_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='ratingreview',
            constraint=models.UniqueConstraint(fields=('reviewer', 'enrollment'), name='unique_course_review_per_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='ratingreview',
            constraint=models.UniqueConstraint(fields=('reviewer', 'event_rsvp'), name='unique_event_review_per_reviewer'),
        ),
    ]
