# Generated by Django 6.0.4 on 2026-07-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_organizationverificationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='chapa', max_length=32)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('ready', 'Ready'), ('restricted', 'Restricted')], default='not_started', max_length=32)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('account_holder_name', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_code', models.CharField(blank=True, max_length=64)),
                ('account_number_last4', models.CharField(blank=True, max_length=4)),
                ('mobile_money_number', models.CharField(blank=True, max_length=32)),
                ('setup_notes', models.TextField(blank=True)),
                ('provider_account_reference', models.CharField(blank=True, max_length=255)),
                ('restricted_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_account', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__name', 'id'],
            },
        ),
    ]
