# Generated by Django 6.0.4 on 2026-07-06 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollmentlessonprogress'),
        ('organizations', '0003_organizationverificationrequest'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('tx_ref', models.CharField(blank=True, max_length=128)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='chapa', max_length=32)),
                ('tx_ref', models.CharField(max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('reversed', 'Reversed')], default='pending', max_length=16)),
                ('checkout_url', models.URLField(blank=True, max_length=500)),
                ('callback_url', models.URLField(blank=True, max_length=500)),
                ('return_url', models.URLField(blank=True, max_length=500)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('provider_method', models.CharField(blank=True, max_length=64)),
                ('provider_mode', models.CharField(blank=True, max_length=16)),
                ('provider_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('verification_data', models.JSONField(blank=True, default=dict)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='courses.courseprogram')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'course_program', 'status'], name='payments_pa_user_id_f280d1_idx'), models.Index(fields=['organization', 'status'], name='payments_pa_organiz_4d9838_idx')],
            },
        ),
    ]
