# Generated by Django 6.0.6 on 2026-07-09 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_initial'),
        ('courses', '0006_courseprogram_auto_issue_service_credit_and_more'),
        ('organizations', '0004_organization_is_suspended_organization_moderated_at_and_more'),
        ('payments', '0003_financialaccount_review_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='automation_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='automation_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='purpose',
            field=models.CharField(choices=[('course_enrollment', 'Course Enrollment'), ('community_service_enrollment', 'Community Service Enrollment')], default='course_enrollment', max_length=40),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='service_credit_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='certificates.servicecreditrecord'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['purpose', 'automation_status'], name='payments_pa_purpose_e0de1e_idx'),
        ),
    ]
