# Generated by Django 6.0.6 on 2026-07-07 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_organization_is_suspended_organization_moderated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('field_interest', 'Field Interest'), ('skill', 'Skill'), ('course_category', 'Course Category'), ('event_category', 'Event Category'), ('opportunity_category', 'Opportunity Category')], max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('normalized_slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_entry_name', models.CharField(blank=True, max_length=120)),
                ('resolved_entry_slug', models.SlugField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomy_suggestions', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_taxonomy_suggestions', to=settings.AUTH_USER_MODEL)),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at', '-id'],
                'indexes': [models.Index(fields=['domain', 'status'], name='taxonomy_ca_domain_4eb1d5_idx'), models.Index(fields=['suggested_by', 'status'], name='taxonomy_ca_suggest_6ede5c_idx'), models.Index(fields=['normalized_slug', 'status'], name='taxonomy_ca_normali_1f5832_idx')],
            },
        ),
        migrations.CreateModel(
            name='ManagedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('field_interest', 'Field Interest'), ('skill', 'Skill'), ('course_category', 'Course Category'), ('event_category', 'Event Category'), ('opportunity_category', 'Opportunity Category')], max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_managed_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['domain', 'name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('domain', 'slug'), name='unique_managed_category_domain_slug')],
            },
        ),
    ]
