# Generated by Django 6.0.6 on 2026-07-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='organization',
            name='offerings_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
